import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  errorText: { color: '#8A2E22', fontSize: 14, lineHeight: 20, marginBottom: 12 },
  successText: { color: '#235D4C', fontSize: 14, lineHeight: 20, marginTop: 10 },
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFDF8',
  },
  shell: {
    backgroundColor: '#F7F4ED',
    flex: 1,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 32,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  appName: {
    color: '#1F211D',
    fontSize: 30,
    fontWeight: '800',
  },
  subtleText: {
    color: '#6D6A61',
    fontSize: 14,
    marginTop: 6,
  },
  runtimeText: {
    color: '#8A2E22',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
    paddingRight: 12,
  },
  runtimeTextMonitoring: {
    color: '#235D4C',
  },
  guardianSwitch: {
    alignItems: 'center',
    borderRadius: 8,
    minWidth: 68,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  switchOn: {
    backgroundColor: '#235D4C',
  },
  switchOff: {
    backgroundColor: '#E6DFD3',
  },
  switchText: {
    fontSize: 15,
    fontWeight: '800',
  },
  switchTextOn: {
    color: '#FFFFFF',
  },
  switchTextOff: {
    color: '#5E584D',
  },
  tabBar: {
    backgroundColor: '#FFFDF8',
    borderColor: '#E5DED2',
    borderTopWidth: 1,
    flexDirection: 'row',
    minHeight: 70,
    paddingHorizontal: 24,
    paddingTop: 9,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 52,
  },
  tabText: {
    color: '#777166',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 5,
  },
  tabTextActive: {
    color: '#235D4C',
  },
  flexItem: {
    flex: 1,
  },
  statusPanel: {
    borderRadius: 8,
    padding: 18,
  },
  statusRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statusLabel: {
    fontSize: 16,
    fontWeight: '700',
  },
  statusHeadline: {
    color: '#1F211D',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 8,
  },
  statusDot: {
    borderRadius: 10,
    height: 20,
    marginLeft: 12,
    width: 20,
  },
  statusDetail: {
    color: '#3D3932',
    fontSize: 16,
    lineHeight: 23,
    marginTop: 14,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  metric: {
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
    borderRadius: 8,
    flex: 1,
    padding: 12,
  },
  metricLabel: {
    color: '#716A5F',
    fontSize: 12,
  },
  metricValue: {
    color: '#24211D',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 4,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#235D4C',
    borderRadius: 14,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 56,
    paddingHorizontal: 18,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#8A2E22',
    borderRadius: 8,
    flex: 1,
    paddingVertical: 15,
  },
  dangerButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  section: {
    marginTop: 24,
  },
  sectionTitle: {
    color: '#1F211D',
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 12,
  },
  infoLine: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  infoLabel: {
    color: '#756F64',
    fontSize: 13,
  },
  infoValue: {
    color: '#25221D',
    fontSize: 16,
    lineHeight: 22,
    marginTop: 5,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryPill: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
    width: '48%',
  },
  summaryLabel: {
    color: '#756F64',
    fontSize: 13,
  },
  summaryValue: {
    color: '#25221D',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 6,
  },
  placeRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 14,
  },
  rowTitle: {
    color: '#24211D',
    fontSize: 17,
    fontWeight: '700',
  },
  rowMeta: {
    color: '#716A5F',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  rowBadge: {
    backgroundColor: '#E7F1EC',
    borderRadius: 8,
    marginLeft: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  rowBadgeText: {
    color: '#235D4C',
    fontSize: 13,
    fontWeight: '800',
  },
  contactRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 14,
  },
  priority: {
    color: '#7A4B00',
    fontSize: 14,
    fontWeight: '800',
    marginLeft: 12,
  },
  inlineActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginLeft: 8,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#EDE6DA',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  iconButtonText: {
    color: '#332F28',
    fontSize: 18,
    fontWeight: '800',
  },
  removeButton: {
    alignItems: 'center',
    backgroundColor: '#F3DDD8',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    marginLeft: 8,
    width: 38,
  },
  removeButtonText: {
    color: '#8A2E22',
    fontSize: 13,
    fontWeight: '800',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    color: '#25221D',
    fontSize: 16,
    marginBottom: 10,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  formLabel: {
    color: '#5F594F',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 4,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  segmentButton: {
    alignItems: 'center',
    backgroundColor: '#ECE6DB',
    borderRadius: 8,
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
  },
  segmentButtonActive: {
    backgroundColor: '#235D4C',
  },
  segmentText: {
    color: '#635E54',
    fontSize: 14,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  stepperRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 14,
  },
  stepperLabel: {
    color: '#24211D',
    fontSize: 16,
    fontWeight: '700',
  },
  stepperValue: {
    color: '#6B655B',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  stepperActions: {
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#235D4C',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  secondaryButtonDisabled: {
    backgroundColor: '#B6AEA2',
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  exerciseRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  exerciseButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#DCD4C8',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
  },
  exerciseButtonText: {
    color: '#235D4C',
    fontSize: 16,
    fontWeight: '800',
  },
  exerciseDangerButton: {
    alignItems: 'center',
    backgroundColor: '#8A2E22',
    borderRadius: 8,
    minHeight: 48,
    justifyContent: 'center',
  },
  exerciseDangerText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  escalationPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  escalationTitle: {
    color: '#25221D',
    fontSize: 17,
    fontWeight: '800',
  },
  escalationDescription: {
    color: '#6B655B',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 6,
  },
  eventRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  eventTime: {
    color: '#716A5F',
    fontSize: 14,
    paddingTop: 14,
    width: 44,
  },
  eventBody: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    padding: 14,
  },
  eventTitle: {
    color: '#25221D',
    fontSize: 16,
    fontWeight: '700',
  },
  eventDescription: {
    color: '#6B655B',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 5,
  },
  eventMeta: {
    color: '#8A8377',
    fontSize: 12,
    marginTop: 8,
  },
  screenTitle: {
    color: '#1F211D',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 18,
  },
  errorBanner: {
    backgroundColor: '#F7E3DE',
    borderRadius: 12,
    color: '#8A2E22',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 14,
    padding: 14,
  },
  tabDot: {
    backgroundColor: '#C9C2B7',
    borderRadius: 4,
    height: 6,
    width: 6,
  },
  tabDotActive: {
    backgroundColor: '#D96F5D',
    width: 18,
  },
  heroStatusCard: {
    borderRadius: 20,
    padding: 20,
  },
  guardianVisual: {
    alignItems: 'center',
    marginBottom: 14,
  },
  guardianHaloOuter: {
    alignItems: 'center',
    borderRadius: 82,
    height: 164,
    justifyContent: 'center',
    width: 164,
  },
  guardianHaloMiddle: {
    alignItems: 'center',
    borderRadius: 65,
    height: 130,
    justifyContent: 'center',
    width: 130,
  },
  guardianHaloCore: {
    alignItems: 'center',
    borderRadius: 48,
    height: 96,
    justifyContent: 'center',
    width: 96,
  },
  guardianShieldImage: {
    height: 72,
    width: 72,
  },
  guardianShieldMark: {
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
    position: 'absolute',
    textAlign: 'center',
    top: 32,
    width: 52,
  },
  centeredStatusLabel: {
    marginTop: 2,
    textAlign: 'center',
  },
  centeredStatusText: {
    textAlign: 'center',
  },
  heroStatusHeadline: {
    color: '#1F211D',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 36,
    marginTop: 8,
  },
  heroStatusDetail: {
    color: '#464239',
    fontSize: 17,
    lineHeight: 25,
    marginTop: 14,
  },
  statusFacts: {
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderRadius: 14,
    flexDirection: 'row',
    marginTop: 20,
    paddingVertical: 14,
  },
  statusFact: {
    flex: 1,
    paddingHorizontal: 14,
  },
  statusFactDivider: {
    backgroundColor: 'rgba(61,57,50,0.16)',
    width: 1,
  },
  statusFactLabel: {
    color: '#777166',
    fontSize: 13,
  },
  statusFactValue: {
    color: '#2C2924',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
    marginTop: 4,
  },
  noticeCard: {
    backgroundColor: '#F1EAE0',
    borderRadius: 14,
    marginTop: 18,
    padding: 16,
  },
  noticeTitle: {
    color: '#4D473E',
    fontSize: 16,
    fontWeight: '800',
  },
  noticeText: {
    color: '#6A6359',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 5,
  },
  sectionHeaderRow: {
    marginTop: 28,
  },
  emptyStateCard: {
    backgroundColor: '#FFFDF9',
    borderColor: '#E5DED2',
    borderRadius: 16,
    borderWidth: 1,
    padding: 20,
  },
  emptyStateTitle: {
    color: '#2C2924',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyStateText: {
    color: '#70695F',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 8,
    textAlign: 'center',
  },
  simpleEventRow: {
    alignItems: 'center',
    borderBottomColor: '#E5DED2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingVertical: 15,
  },
  simpleEventTime: {
    color: '#786F64',
    fontSize: 15,
    marginRight: 16,
    width: 48,
  },
  simpleEventTitle: {
    color: '#2C2924',
    fontSize: 17,
    fontWeight: '700',
  },
  simpleEventMeta: {
    color: '#837B70',
    fontSize: 13,
    marginTop: 4,
  },
  footprintPrivacyCard: {
    backgroundColor: '#E9F1ED',
    borderRadius: 16,
    marginBottom: 16,
    padding: 18,
  },
  footprintPrivacyTitle: {
    color: '#235D4C',
    fontSize: 18,
    fontWeight: '800',
  },
  footprintPrivacyText: {
    color: '#50685F',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 6,
  },
  footprintEmptyCard: {
    marginTop: 0,
  },
  footprintList: {
    backgroundColor: '#FFFDF9',
    borderColor: '#E5DED2',
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
  },
  footprintRow: {
    flexDirection: 'row',
    minHeight: 88,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  footprintMarker: {
    alignItems: 'center',
    marginRight: 14,
    paddingTop: 7,
    width: 20,
  },
  footprintMarkerDot: {
    backgroundColor: '#D96F5D',
    borderColor: '#F4DED7',
    borderRadius: 8,
    borderWidth: 4,
    height: 16,
    width: 16,
  },
  footprintTitle: {
    color: '#2C2924',
    fontSize: 18,
    fontWeight: '800',
  },
  footprintLocation: {
    color: '#625D54',
    fontSize: 15,
    marginTop: 5,
  },
  footprintTime: {
    color: '#8A8377',
    fontSize: 14,
    marginTop: 6,
  },
  placeSummaryCard: {
    backgroundColor: '#E6EFEA',
    borderRadius: 20,
    padding: 20,
  },
  placeSummaryEyebrow: {
    color: '#477263',
    fontSize: 14,
    fontWeight: '800',
  },
  placeSummaryTitle: {
    color: '#1E4C3E',
    fontSize: 25,
    fontWeight: '800',
    marginTop: 7,
  },
  placeSummaryText: {
    color: '#49665C',
    fontSize: 16,
    lineHeight: 23,
    marginTop: 8,
  },
  placeList: {
    gap: 12,
    marginTop: 16,
  },
  placeCard: {
    backgroundColor: '#FFFDF9',
    borderColor: '#E4DDD2',
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
  },
  placeCardMain: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 82,
    padding: 14,
  },
  placeIcon: {
    alignItems: 'center',
    backgroundColor: '#F4DED7',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    marginRight: 13,
    width: 44,
  },
  placeIconText: {
    color: '#9A4E42',
    fontSize: 17,
    fontWeight: '800',
  },
  guardianBadge: {
    backgroundColor: '#E5F0EA',
    borderRadius: 12,
    marginLeft: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  guardianBadgeText: {
    color: '#235D4C',
    fontSize: 13,
    fontWeight: '800',
  },
  guardianBadgeWarning: {
    backgroundColor: '#F6E3DE',
  },
  guardianBadgeWarningText: {
    color: '#8A2E22',
  },
  guardianBadgePaused: {
    backgroundColor: '#E9E5DE',
  },
  guardianBadgePausedText: {
    color: '#6E675E',
  },
  placeManagePanel: {
    backgroundColor: '#F6F1E9',
    borderTopColor: '#E4DDD2',
    borderTopWidth: 1,
    padding: 14,
  },
  choiceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  choiceRowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  choiceButton: {
    alignItems: 'center',
    backgroundColor: '#EEE8DE',
    borderColor: '#EEE8DE',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 72,
    paddingHorizontal: 10,
  },
  choiceButtonActive: {
    backgroundColor: '#235D4C',
    borderColor: '#235D4C',
  },
  choiceButtonText: {
    color: '#5E584E',
    fontSize: 15,
    fontWeight: '800',
  },
  choiceButtonTextActive: {
    color: '#FFFFFF',
  },
  textDangerButton: {
    alignItems: 'center',
    marginTop: 15,
    minHeight: 44,
    paddingVertical: 10,
  },
  textDangerButtonText: {
    color: '#9A3D31',
    fontSize: 15,
    fontWeight: '700',
  },
  inlineNoticeButton: {
    backgroundColor: '#F7E3DE',
    borderRadius: 14,
    marginTop: 14,
    padding: 15,
  },
  inlineNoticeTitle: {
    color: '#8A2E22',
    fontSize: 16,
    fontWeight: '800',
  },
  inlineNoticeText: {
    color: '#8A2E22',
    fontSize: 14,
    marginTop: 4,
  },
  placeEmptyCard: {
    alignItems: 'center',
    backgroundColor: '#FFFDF9',
    borderColor: '#E4DDD2',
    borderRadius: 20,
    borderWidth: 1,
    padding: 24,
  },
  emptyPlaceIcon: {
    alignItems: 'center',
    backgroundColor: '#F4DED7',
    borderRadius: 29,
    height: 58,
    justifyContent: 'center',
    marginBottom: 16,
    width: 58,
  },
  emptyPlaceIconText: {
    color: '#A45143',
    fontSize: 30,
    fontWeight: '800',
  },
  setupSteps: {
    alignSelf: 'stretch',
    gap: 12,
    marginTop: 22,
  },
  setupStep: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  setupStepNumber: {
    alignItems: 'center',
    backgroundColor: '#E5F0EA',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    marginRight: 12,
    width: 28,
  },
  setupStepNumberText: {
    color: '#235D4C',
    fontSize: 14,
    fontWeight: '800',
  },
  setupStepText: {
    color: '#49443C',
    fontSize: 16,
  },
  addPlaceCard: {
    backgroundColor: '#FFFDF9',
    borderColor: '#E4DDD2',
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 18,
    padding: 18,
  },
  addPlaceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  addPlaceTitle: {
    color: '#24211D',
    fontSize: 22,
    fontWeight: '800',
  },
  cancelText: {
    color: '#6B655B',
    fontSize: 16,
    fontWeight: '700',
    padding: 6,
  },
  locatingCard: {
    backgroundColor: '#F1ECE4',
    borderRadius: 14,
    padding: 18,
  },
  locatingTitle: {
    color: '#343029',
    fontSize: 18,
    fontWeight: '800',
  },
  locatingText: {
    color: '#6B655B',
    fontSize: 15,
    marginTop: 6,
  },
  formErrorCard: {
    backgroundColor: '#F7E3DE',
    borderRadius: 14,
    padding: 15,
  },
  errorActions: {
    flexDirection: 'row',
    gap: 24,
  },
  linkText: {
    color: '#235D4C',
    fontSize: 16,
    fontWeight: '800',
    paddingVertical: 5,
  },
  locationSuccessCard: {
    alignItems: 'center',
    backgroundColor: '#E6F0EA',
    borderRadius: 14,
    flexDirection: 'row',
    marginBottom: 20,
    padding: 15,
  },
  locationSuccessMark: {
    color: '#235D4C',
    fontSize: 24,
    fontWeight: '900',
    marginRight: 12,
  },
  locationSuccessTitle: {
    color: '#235D4C',
    fontSize: 17,
    fontWeight: '800',
  },
  locationSuccessText: {
    color: '#537165',
    fontSize: 14,
    marginTop: 3,
  },
  fieldHelpText: {
    color: '#777065',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 10,
  },
  pageFootnote: {
    color: '#827A6F',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 16,
    textAlign: 'center',
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 10,
    minHeight: 40,
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#235D4C',
    fontSize: 17,
    fontWeight: '700',
  },
  permissionCard: {
    backgroundColor: '#FFFDF9',
    borderColor: '#E4DDD2',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
  },
  permissionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 58,
  },
  permissionLabel: {
    color: '#343029',
    fontSize: 17,
    fontWeight: '700',
  },
  permissionValue: {
    color: '#686157',
    fontSize: 15,
  },
  permissionDivider: {
    backgroundColor: '#EAE3D8',
    height: 1,
  },
  settingHelpText: {
    color: '#70695F',
    fontSize: 15,
    lineHeight: 23,
    marginTop: 14,
  },
  shortcutInstallText: {
    color: '#3F3A33',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 14,
  },
  shortcutFootnote: {
    color: '#756E64',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
  secondaryOutlineButton: {
    alignItems: 'center',
    borderColor: '#CFC7BA',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 52,
  },
  secondaryOutlineButtonText: {
    color: '#235D4C',
    fontSize: 16,
    fontWeight: '800',
  },
  guardianSettingCard: {
    backgroundColor: '#E6F0EA',
    borderRadius: 20,
    padding: 20,
  },
  guardianSettingPaused: {
    backgroundColor: '#EEE8DF',
  },
  guardianSettingHeader: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  guardianSettingLabel: {
    color: '#537166',
    fontSize: 14,
    fontWeight: '800',
  },
  guardianSettingTitle: {
    color: '#234E40',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 6,
  },
  guardianSettingDetail: {
    color: '#52685F',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
  },
  guardianStatusDot: {
    backgroundColor: '#3E806A',
    borderRadius: 7,
    height: 14,
    marginLeft: 12,
    width: 14,
  },
  guardianStatusDotPaused: {
    backgroundColor: '#A79F93',
  },
  settingsGroup: {
    backgroundColor: '#FFFDF9',
    borderColor: '#E4DDD2',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 18,
    overflow: 'hidden',
    paddingHorizontal: 16,
  },
  settingsRow: {
    alignItems: 'center',
    borderBottomColor: '#EAE3D8',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 66,
  },
  settingsRowLabel: {
    color: '#2F2C27',
    fontSize: 17,
    fontWeight: '700',
  },
  settingsRowRight: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  settingsRowValue: {
    color: '#81796E',
    fontSize: 15,
  },
  settingsChevron: {
    color: '#9B9388',
    fontSize: 26,
    marginLeft: 8,
  },
  quietButton: {
    alignItems: 'center',
    borderColor: '#D7CFC3',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 52,
  },
  quietButtonText: {
    color: '#6D665C',
    fontSize: 16,
    fontWeight: '700',
  },
  aboutCard: {
    marginTop: 28,
    paddingVertical: 8,
  },
  aboutTitle: {
    color: '#49443C',
    fontSize: 17,
    fontWeight: '800',
  },
  aboutText: {
    color: '#7A7368',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 5,
  },
  resetLink: {
    alignItems: 'center',
    marginTop: 18,
    minHeight: 46,
    padding: 12,
  },
  resetLinkText: {
    color: '#9A5348',
    fontSize: 14,
  },
});
