import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  errorText: { color: '#8A2E22', fontSize: 14, lineHeight: 20, marginBottom: 12 },
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F4ED',
  },
  shell: {
    flex: 1,
  },
  container: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  appName: {
    color: '#1F211D',
    fontSize: 30,
    fontWeight: '800',
  },
  subtleText: {
    color: '#6D6A61',
    fontSize: 14,
    marginTop: 6,
  },
  guardianSwitch: {
    alignItems: 'center',
    borderRadius: 8,
    minWidth: 68,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  switchOn: {
    backgroundColor: '#235D4C',
  },
  switchOff: {
    backgroundColor: '#E6DFD3',
  },
  switchText: {
    fontSize: 15,
    fontWeight: '800',
  },
  switchTextOn: {
    color: '#FFFFFF',
  },
  switchTextOff: {
    color: '#5E584D',
  },
  tabBar: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  tabButton: {
    alignItems: 'center',
    backgroundColor: '#ECE6DB',
    borderRadius: 8,
    flex: 1,
    minHeight: 40,
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#1F211D',
  },
  tabText: {
    color: '#635E54',
    fontSize: 14,
    fontWeight: '700',
  },
  tabTextActive: {
    color: '#FFFFFF',
  },
  flexItem: {
    flex: 1,
  },
  statusPanel: {
    borderRadius: 8,
    padding: 18,
  },
  statusRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statusLabel: {
    fontSize: 16,
    fontWeight: '700',
  },
  statusHeadline: {
    color: '#1F211D',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 8,
  },
  statusDot: {
    borderRadius: 10,
    height: 20,
    marginLeft: 12,
    width: 20,
  },
  statusDetail: {
    color: '#3D3932',
    fontSize: 16,
    lineHeight: 23,
    marginTop: 14,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  metric: {
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
    borderRadius: 8,
    flex: 1,
    padding: 12,
  },
  metricLabel: {
    color: '#716A5F',
    fontSize: 12,
  },
  metricValue: {
    color: '#24211D',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 4,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#235D4C',
    borderRadius: 8,
    flex: 1,
    paddingVertical: 15,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#8A2E22',
    borderRadius: 8,
    flex: 1,
    paddingVertical: 15,
  },
  dangerButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  section: {
    marginTop: 24,
  },
  sectionTitle: {
    color: '#1F211D',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 12,
  },
  infoLine: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  infoLabel: {
    color: '#756F64',
    fontSize: 13,
  },
  infoValue: {
    color: '#25221D',
    fontSize: 16,
    lineHeight: 22,
    marginTop: 5,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryPill: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
    width: '48%',
  },
  summaryLabel: {
    color: '#756F64',
    fontSize: 13,
  },
  summaryValue: {
    color: '#25221D',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 6,
  },
  placeRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 14,
  },
  rowTitle: {
    color: '#24211D',
    fontSize: 17,
    fontWeight: '700',
  },
  rowMeta: {
    color: '#716A5F',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  rowBadge: {
    backgroundColor: '#E7F1EC',
    borderRadius: 8,
    marginLeft: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  rowBadgeText: {
    color: '#235D4C',
    fontSize: 13,
    fontWeight: '800',
  },
  contactRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 14,
  },
  priority: {
    color: '#7A4B00',
    fontSize: 14,
    fontWeight: '800',
    marginLeft: 12,
  },
  inlineActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginLeft: 8,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#EDE6DA',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  iconButtonText: {
    color: '#332F28',
    fontSize: 18,
    fontWeight: '800',
  },
  removeButton: {
    alignItems: 'center',
    backgroundColor: '#F3DDD8',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    marginLeft: 8,
    width: 38,
  },
  removeButtonText: {
    color: '#8A2E22',
    fontSize: 13,
    fontWeight: '800',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    color: '#25221D',
    fontSize: 16,
    marginBottom: 10,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  formLabel: {
    color: '#5F594F',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 4,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  segmentButton: {
    alignItems: 'center',
    backgroundColor: '#ECE6DB',
    borderRadius: 8,
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
  },
  segmentButtonActive: {
    backgroundColor: '#235D4C',
  },
  segmentText: {
    color: '#635E54',
    fontSize: 14,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  stepperRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    padding: 14,
  },
  stepperLabel: {
    color: '#24211D',
    fontSize: 16,
    fontWeight: '700',
  },
  stepperValue: {
    color: '#6B655B',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  stepperActions: {
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#235D4C',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  secondaryButtonDisabled: {
    backgroundColor: '#B6AEA2',
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  exerciseRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  exerciseButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#DCD4C8',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
  },
  exerciseButtonText: {
    color: '#235D4C',
    fontSize: 16,
    fontWeight: '800',
  },
  exerciseDangerButton: {
    alignItems: 'center',
    backgroundColor: '#8A2E22',
    borderRadius: 8,
    minHeight: 48,
    justifyContent: 'center',
  },
  exerciseDangerText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  escalationPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  escalationTitle: {
    color: '#25221D',
    fontSize: 17,
    fontWeight: '800',
  },
  escalationDescription: {
    color: '#6B655B',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 6,
  },
  eventRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  eventTime: {
    color: '#716A5F',
    fontSize: 14,
    paddingTop: 14,
    width: 44,
  },
  eventBody: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED2',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    padding: 14,
  },
  eventTitle: {
    color: '#25221D',
    fontSize: 16,
    fontWeight: '700',
  },
  eventDescription: {
    color: '#6B655B',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 5,
  },
  eventMeta: {
    color: '#8A8377',
    fontSize: 12,
    marginTop: 8,
  },
});
